enum ErrorCodes {
  UNKNOWN = "UNKNOWN",
  INVALID_ADAPTER = "INVALID_ADAPTER",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_MODEL_ADAPTER = "INVALID_MODEL_ADAPTER",
  INVALID_MODEL_SLUG = "INVALID_MODEL_SLUG",
}

export default ErrorCodes;
